services:
  web:
    image: retyn-avm
    container_name: retyn-avm
    ports:
      - "8003:8000"
    env_file:
     - .env
    depends_on:
      - redis
    environment:
      - REDIS_ENABLED=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  
  redis:
    image: redis:7-alpine
    container_name: retyn-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    restart: unless-stopped

volumes:
  redis_data:

